### ISSUE TITLE
Arapa's Chinese online store will soon cease operations

### ISSUE THREAD

**Issue by VMatrices** [ichorid/arparascam#2]
[https://mall.jd.com/index-12087820.html?from=pc](url)

![image](https://user-images.githubusercontent.com/24680533/197311506-931dc3bf-e244-4d5f-a415-82de752cd574.png)

**Comment by vrpixel** [comment]
that's awesome.
i hope people behind arpara live a long and fulfilled life, while kickstarter backers/worshippers are left with nothing.

you all brought it up upon yourself.
